- hosts: all
  tasks:
  - apt:
      name: '{{ item }}'
      state: present
    become: true
    name: sudo apt-get install libprotobuf-dev libleveldb-dev libsnappy-dev libopencv-dev
      libhdf5-serial-dev protobuf-compiler
    with_items:
    - libprotobuf-dev
    - libleveldb-dev
    - libsnappy-dev
    - libopencv-dev
    - libhdf5-serial-dev
    - protobuf-compiler
  - apt:
      install_recommends: 'no'
      name:
      - libboost-all-dev
      state: present
    become: true
    name: sudo apt-get install --no-install-recommends libboost-all-dev
  - apt:
      name: '{{ item }}'
      state: present
    become: true
    name: sudo apt-get install libgflags-dev libgoogle-glog-dev liblmdb-dev
    with_items:
    - libgflags-dev
    - libgoogle-glog-dev
    - liblmdb-dev

